name: Test Docker browsers latest
on: workflow_dispatch
jobs:
  docker-browsers:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
        working-directory: examples/basic
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge, electron, firefox]
    # from https://hub.docker.com/r/cypress/browsers/tags
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - run: node -v
      - run: npm ci
      - run: npx cypress info
      - run: npx cypress run --browser ${{ matrix.browser }}
